deepspeed --master_port 29400 --include localhost:0,1 llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path /path/to/your_model \
    --version v1 \
    --tune_dsu True \
    --align_loss_weight "$ALIGN_LOSS_WEIGHT" \
    --dsu_reduction_ratio "$DSU_REDUCTION_RATIO" \
    --data_path /path/to/your_data \
    --image_folder /path/to/your_data \
    --vision_tower /path/to/your_vision_tower \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir /path/to/your_checkpoint_dir \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 300 \
    --save_total_limit 5 \
    --learning_rate "$LEARNING_RATE" \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

python ./scripts/merge_lora_weights.py \
    --model-path /path/to/your_checkpoint_dir \
    --model-base /path/to/your_model \
    --save-model-path /path/to/your_checkpoint_dir